version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder:wine-chrome
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npx envinfo
      - run: npm i -g n && n latest
      - run: yarn
      - run: yarn release --linux
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build:
    jobs:
      - build
